name: yandex_geocoder
description: API to translate geographic coordinates into an address and vice versa
version: 2.0.1
repository: https://github.com/MadBrains/Yandex-Geocoder-Flutter
issue_tracker: https://github.com/MadBrains/Yandex-Geocoder-Flutter/issues
homepage: https://madbrains.ru/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  http: ^0.13.3
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.3